### DO NOT EDIT THIS FILE ###
export OB_TYPE          := standard
export OB_DEFCONFIG_DIR := ${CURDIR}/configs
export OB_DOCKER_DIR    := ${CURDIR}/configs/docker

include third-party/openbar/main.mk
### DO NOT EDIT THIS FILE ###
